name: CI Workflow
on:
  push:
    branches:
      - master
  pull_request:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest 
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Build
        uses: cedrickring/golang-action@1.3.0
        env:
          GO111MODULE: "on"